## **Data Preprocessing**

In [ ]:
import numpy as np
import cv2 as cv
import random
import os
import matplotlib.pyplot as plt
import pickle
%matplotlib inline
import pandas

In [ ]:
DIRECTORY = '/content/drive/MyDrive/dataset'
# a raw string(r'...') is used to treat backslash(\) as a normal character
CATEGORIES = ['mammooty','mohanlal']

In [ ]:
IMG_SIZE = 224

data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        label = CATEGORIES.index(category)
        img_arr = cv.imread(img_path, cv.IMREAD_GRAYSCALE)
        img_arr = cv.resize(img_arr, (IMG_SIZE, IMG_SIZE))
        data.append([img_arr, label])
# labelling the data


In [ ]:
random.shuffle(data)
# to shuffle the data

In [ ]:
X = []
y = []

for features, labels in data:
    X.append(features)
    y.append(labels)

In [ ]:
X = np.array(X)
y = np.array(y)
# changed X & y into arrays and stored it in respective variables

In [ ]:
X

array([[[ 18,  18,  17, ...,  36,  31,  31],
        [ 18,  18,  17, ...,  36,  31,  31],
        [ 17,  17,  16, ...,  37,  34,  34],
        ...,
        [ 61,  61,  66, ..., 196, 195, 195],
        [ 60,  60,  66, ..., 193, 193, 193],
        [ 60,  60,  66, ..., 193, 193, 193]],

       [[ 24,  24,  24, ...,  26,  24,  23],
        [ 25,  25,  25, ...,  25,  23,  23],
        [ 28,  27,  27, ...,  24,  22,  22],
        ...,
        [ 89,  89,  89, ...,  36,  38,  38],
        [ 90,  90,  89, ...,  35,  37,  37],
        [ 90,  90,  89, ...,  35,  37,  37]],

       [[109, 110, 113, ...,  38,  44,  45],
        [112, 113, 117, ...,  37,  43,  44],
        [131, 132, 138, ...,  35,  39,  40],
        ...,
        [129, 129, 129, ...,  99, 101, 101],
        [129, 129, 129, ...,  98,  99,  99],
        [129, 129, 129, ...,  99,  99,  99]],

       ...,

       [[130, 131, 134, ..., 233, 233, 233],
        [131, 131, 133, ..., 233, 233, 233],
        [133, 132, 131, ..., 233, 232, 232

In [ ]:
y

array([0, 1, 0, ..., 1, 1, 1])

In [ ]:
X = pickle.dump(X,open('X.pkl', 'wb'))
y = pickle.dump(y,open('y.pkl', 'wb'))

# storing the data in a pickle file

## **Building the CNN**

In [ ]:
import pickle

In [ ]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [ ]:
X

array([[[ 18,  18,  17, ...,  36,  31,  31],
        [ 18,  18,  17, ...,  36,  31,  31],
        [ 17,  17,  16, ...,  37,  34,  34],
        ...,
        [ 61,  61,  66, ..., 196, 195, 195],
        [ 60,  60,  66, ..., 193, 193, 193],
        [ 60,  60,  66, ..., 193, 193, 193]],

       [[ 24,  24,  24, ...,  26,  24,  23],
        [ 25,  25,  25, ...,  25,  23,  23],
        [ 28,  27,  27, ...,  24,  22,  22],
        ...,
        [ 89,  89,  89, ...,  36,  38,  38],
        [ 90,  90,  89, ...,  35,  37,  37],
        [ 90,  90,  89, ...,  35,  37,  37]],

       [[109, 110, 113, ...,  38,  44,  45],
        [112, 113, 117, ...,  37,  43,  44],
        [131, 132, 138, ...,  35,  39,  40],
        ...,
        [129, 129, 129, ...,  99, 101, 101],
        [129, 129, 129, ...,  98,  99,  99],
        [129, 129, 129, ...,  99,  99,  99]],

       ...,

       [[130, 131, 134, ..., 233, 233, 233],
        [131, 131, 133, ..., 233, 233, 233],
        [133, 132, 131, ..., 233, 232, 232

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
X = X/255

In [ ]:
X

array([[[0.07058824, 0.07058824, 0.06666667, ..., 0.14117647,
         0.12156863, 0.12156863],
        [0.07058824, 0.07058824, 0.06666667, ..., 0.14117647,
         0.12156863, 0.12156863],
        [0.06666667, 0.06666667, 0.0627451 , ..., 0.14509804,
         0.13333333, 0.13333333],
        ...,
        [0.23921569, 0.23921569, 0.25882353, ..., 0.76862745,
         0.76470588, 0.76470588],
        [0.23529412, 0.23529412, 0.25882353, ..., 0.75686275,
         0.75686275, 0.75686275],
        [0.23529412, 0.23529412, 0.25882353, ..., 0.75686275,
         0.75686275, 0.75686275]],

       [[0.09411765, 0.09411765, 0.09411765, ..., 0.10196078,
         0.09411765, 0.09019608],
        [0.09803922, 0.09803922, 0.09803922, ..., 0.09803922,
         0.09019608, 0.09019608],
        [0.10980392, 0.10588235, 0.10588235, ..., 0.09411765,
         0.08627451, 0.08627451],
        ...,
        [0.34901961, 0.34901961, 0.34901961, ..., 0.14117647,
         0.14901961, 0.14901961],
        [0.3

In [ ]:
X.shape

(1004, 224, 224)

In [ ]:
X = X.reshape(-1, 224, 224, 1)

In [ ]:
X.shape

(1004, 224, 224, 1)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [ ]:
# Initialising the CNN
model = Sequential()

In [ ]:
# Step 1 - Convolution
model.add(Conv2D(64,(3,3), activation='relu'))
# Step 2 - Pooling
model.add(MaxPooling2D((2,2)))

# Adding a second convolutional layer
model.add(Conv2D(64,(3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))

# Step 3 - Flattening
model.add(Flatten())

# Step 4 - Full Connection
model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

# Step 5 - Output Layer
model.add(Dense(2, activation= 'sigmoid'))

In [ ]:
# Compiling the CNN
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])


In [ ]:
model.fit(X, y, epochs=10, validation_split=0.2)

Epoch 1/10
26/26 [==============================] - 65s 2s/step - loss: 1.1536 - accuracy: 0.6513 - val_loss: 0.6013 - val_accuracy: 0.7313
Epoch 2/10
26/26 [==============================] - 66s 3s/step - loss: 0.5247 - accuracy: 0.7410 - val_loss: 0.4005 - val_accuracy: 0.7960
Epoch 3/10
26/26 [==============================] - 66s 3s/step - loss: 0.3344 - accuracy: 0.8543 - val_loss: 0.2423 - val_accuracy: 0.9154
Epoch 4/10
26/26 [==============================] - 64s 2s/step - loss: 0.1660 - accuracy: 0.9402 - val_loss: 0.1694 - val_accuracy: 0.9303
Epoch 5/10
26/26 [==============================] - 64s 2s/step - loss: 0.0876 - accuracy: 0.9726 - val_loss: 0.1223 - val_accuracy: 0.9403
Epoch 6/10
26/26 [==============================] - 64s 2s/step - loss: 0.0479 - accuracy: 0.9900 - val_loss: 0.1046 - val_accuracy: 0.9602
Epoch 7/10
26/26 [==============================] - 64s 2s/step - loss: 0.0214 - accuracy: 0.9975 - val_loss: 0.0829 - val_accuracy: 0.9751
Epoch 8/10
26/26 [==

In [ ]:
scores = model.evaluate(X,y,verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))
#to know accuracy of model

Accuracy: 99.30%


In [ ]:
X.shape

(1004, 224, 224, 1)

In [ ]:
model.save('cnn.model',save_format='h5')
#to save the model

# **Prediction**

In [ ]:
import numpy as np
import cv2
import keras

In [ ]:
CATEGORIES = ['mammooty', 'mohanlal']


def image(path):
    img = cv.imread(path, cv.IMREAD_GRAYSCALE)
    new_arr = cv.resize(img, (224, 224))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 224,224, 1)
    return new_arr
#preprocessing the user input

In [ ]:
model = keras.models.load_model('cnn.model')

In [ ]:
result = model.predict([image('/content/drive/MyDrive/dataset/mammooty/mammooty132.png')])
if result[0][0] == 1:
    prediction = 'mamooty'
elif result[0][0] == 0:
    prediction = 'mohanlal'
else:
    prediction = 'I dont know this guy!'
print(prediction)

1/1 [==============================] - 0s 190ms/step
mamooty
